namespace: bar

deployments:
  backend:
    devel:
      enabled: true
      labels:
        system.ardikabs.com/application: bar
      helm:
        valueFiles:
          - .values.devel.yaml
          - values.devel.yaml


    stg:
      enabled: true
      labels:
        system.ardikabs.com/application: bar
      helm:
        valueFiles:
          - .values.stg.yaml
          - values.stg.yaml

    prd:
      enabled: false
